# Generated by Django 3.2 on 2024-12-28 04:00

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20241227_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='reviewsuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='reviewsuser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=9),
        ),
        migrations.AlterField(
            model_name='reviewsuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким username уже существует.'}, help_text='Обязательное поле. Не более 150 символов. Только буквы, цифры и @/./+/-/_. Слова кроме "me".', max_length=150, unique=True, validators=[reviews.models.UsernameValidator()]),
        ),
    ]
